// <auto-generated />
namespace HostelManagment.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class HMSMigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(HMSMigration));
        
        string IMigrationMetadata.Id
        {
            get { return "202202061841568_HMSMigration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
